### ISSUE TITLE
Not able to install the chart

### ISSUE THREAD

**Issue by imshashank** [8gears/n8n-helm-chart#108] opened 2024-07-13 16:50 UTC
Hi, I am trying to install this chart using the below command:

```
helm install my-n8n oci://8gears.container-registry.com/library/n8n --version 0.24.3
```

But I am getting this error:

```
Error: INSTALLATION FAILED: failed to download "oci://8gears.container-registry.com/library/n8n" at version "0.24.3"
```

**Comment by Vad1mo** [comment] 2024-07-13 17:02
- try 0.24.4
- try 
```sh
❯ helm pull oci://8gears.container-registry.com/library/n8n --version 0.24.3
Pulled: 8gears.container-registry.com/library/n8n:0.24.3
Digest: sha256:66c2d5d28300efbb82b8e23d5d2814d34e877ac443234155e14c18a1fa4a9af0


```

**Comment by Vad1mo** [comment] 2024-07-16 16:51
I'm going ahead and close this issue, please reopen if the issue is not resolved.

**Closed by Vad1mo** 2024-07-16 16:51 UTC

**Comment by imshashank** [comment] 2024-07-18 08:29
Thanks for the help. 
Getting this error now ->
```
helm pull oci://8gears.container-registry.com/library/n8n --version 0.24.4
Error: no cached repo found. (try 'helm repo update'): open /Users/shashank/Library/Caches/helm/repository/timescaledb-index.yaml: no such file or directory
```

**Comment by imshashank** [comment] 2024-07-18 08:36
Thanks a lot for the help, it works now.
